### ISSUE TITLE
[BUG]: Fail on memtier_benchmark-10Mkeys-load-hash-5-fields-with-1000B-values-pipeline-10.yml

### ISSUE THREAD

**Issue by markovamaria** [redis/redis-benchmarks-specification#104]
Fail on test memtier_benchmark-10Mkeys-load-hash-5-fields-with-1000B-values-pipeline-10.yml, started from v30, still exist in [latest head](https://github.com/redis/redis-benchmarks-specification/commit/9bd0473cb2b569d84c51f0422e2322587a5b0e62) 
**To Reproduce**
```
$ redis-benchmarks-spec-client-runner --db_server_host localhost --db_server_port 6379 --client_aggregated_results_folder ./test --test memtier_benchmark-10Mkeys-load-hash-5-fields-with-1000B-values-pipeline-10.yml
```
**Expected behavior**
Successful run with results

**Screenshots/CLI snippets**
Test Kills server:
```
$ ./src/redis-server --port 6379 --dir ~/logs --logfile fail.log --dbfilename my_db.rdb
Killed
```
Error message:
```
2022-05-13 17:37:32 CRITICAL Some unexpected exception was caught during local work. Failing test....
2022-05-13 17:37:32 CRITICAL <class 'redis.exceptions.ConnectionError'>
2022-05-13 17:37:32 INFO Tearing down setup

------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 1398, in get_connection
    if connection.can_read():
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 812, in can_read
    return self._parser.can_read(timeout)
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 317, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 224, in can_read
    return bool(self.length) or self._read_from_socket(
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 197, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 614, in connect
    sock = self.retry.call_with_retry(
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 615, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 680, in _connect
    raise err
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 668, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis_benchmarks_specification/__runner__/runner.py", line 413, in process_self_contained_coordinator_stream
    r.flushall()
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/commands/core.py", line 901, in flushall
    return self.execute_command("FLUSHALL", *args, **kwargs)
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/client.py", line 1224, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 1402, in get_connection
    connection.connect()
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis/connection.py", line 620, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Work/exp_flush/env/bin/redis-benchmarks-spec-client-runner", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis_benchmarks_specification/__runner__/runner.py", line 129, in main
    process_self_contained_coordinator_stream(
  File "/home/ubuntu/Work/exp_flush/env/lib/python3.8/site-packages/redis_benchmarks_specification/__runner__/runner.py", line 517, in process_self_contained_coordinator_stream
    full_result_path, dest_fpath
UnboundLocalError: local variable 'full_result_path' referenced before assignment

```

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - PyPi version package - latest default
 - Platfrom x86_64

**Comment by slice4e** [comment]
Hi Maria - I just tried it and it works for me. 
Does the test fail when run independently? Or when run as part of the test suite?

**Comment by MarkovaMaria** [comment]
> Hi Maria - I just tried it and it works for me. Does the test fail when run independently? Or when run as part of the test suite?

Both - Independently and as part of test suite too.

**Comment by MarkovaMaria** [comment]
Suppose, issue and reproducing steps can be similar too https://github.com/redis/redis-benchmarks-specification/issues/105
Seems issue is fluctuating. How I caught it again: 
Run this bench, wait really looong time (about 2 hours), not sure was it long execution or benchmark was hanging. 
Killed server manually, bench aborted. 

Re-run server, re-run bench, got fail. 
```
2022-05-13 22:49:57 CRITICAL Some unexpected exception was caught during local work. Failing test....
2022-05-13 22:49:57 CRITICAL <class 'redis.exceptions.ConnectionError'>
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Work/env3/lib/python3.8/site-packages/redis/connection.py", line 1398, in get_connection
    if connection.can_read():
  File "/home/ubuntu/Work/env3/lib/python3.8/site-packages/redis/connection.py", line 812, in can_read
    return self._parser.can_read(timeout)
  File "/home/ubuntu/Work/env3/lib/python3.8/site-packages/redis/connection.py", line 317, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/ubuntu/Work/env3/lib/python3.8/site-packages/redis/connection.py", line 224, in can_read
    return bool(self.length) or self._read_from_socket(
  File "/home/ubuntu/Work/env3/lib/python3.8/site-packages/redis/connection.py", line 197, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
...
```

**Comment by markovamaria** [comment]
Verified that issue is still actual and appeared in case of using option "--dbfilename my_db.rdb". 
There is no issue with "--save "" "  used in redis-server running line.

**Comment by markovamaria** [comment]
Wrong execution way (--dbfilename was used with run-server command) lead to errors. Should be run with --save no. 
Update to readme is suggested.

Closing issue as not relevant.
