### ISSUE TITLE
[BUG]: triggering new tests fails

### ISSUE THREAD

**Issue by slice4e** [redis/redis-benchmarks-specification#119]
```
(...)
Traceback (most recent call last):
  File "/usr/local/bin/redis-benchmarks-spec-sc-coordinator", line 5, in <module>
    from redis_benchmarks_specification.__self_contained_coordinator__.self_contained_coordinator import main
  File "/usr/local/lib/python3.8/dist-packages/redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py", line 27, in <module>
    from redis_benchmarks_specification.__self_contained_coordinator__.runners import (
  File "/usr/local/lib/python3.8/dist-packages/redis_benchmarks_specification/__self_contained_coordinator__/runners.py", line 57, in <module>
    from redis_benchmarks_specification.__self_contained_coordinator__.docker import (
  File "/usr/local/lib/python3.8/dist-packages/redis_benchmarks_specification/__self_contained_coordinator__/docker.py", line 8, in <module>
    from redis_benchmarks_specification.__self_contained_coordinator__.self_contained_coordinator import (
ImportError: cannot import name 'generate_standalone_redis_server_args' from partially initialized module 'redis_benchmarks_specification.__self_contained_coordinator__.self_contained_coordinator' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py)
```

**Comment by filipecosta90** [comment]
Plan: 
- extend coverage of self cointained coordinator tool. By adding the same type of tests to `redis-benchmarks-spec-sc-coordinator` like we're adding in PR #138 . 
- Assuming we get a green CI on the above we can close this issue
cc @ofekshenawa
