### ISSUE TITLE
[BUG]: redis-benchmarks-spec-cli fails

### ISSUE THREAD

**Issue by slice4e** [redis/redis-benchmarks-specification#183]
**To Reproduce**
1.  python3 -m pip install redis-benchmarks-specification==0.1.61
2.  redis-benchmarks-spec-cli --use-branch --branch unstable --last_n 1 --redis_port 12010 --redis_host benchmarks.redislabs.com --redis_pass 0af07a81af09df7d575f81f524b20276 --dry-run

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/redis-benchmarks-spec-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis_benchmarks_specification/__cli__/cli.py", line 53, in main
    trigger_tests_cli_command_logic(args, project_name, project_version)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/redis_benchmarks_specification/__cli__/cli.py", line 103, in trigger_tests_cli_command_logic
    <= datetime.datetime.utcfromtimestamp(commit_datetime.timestamp())
AttributeError: 'str' object has no attribute 'timestamp'

**Environment (please complete the following information):**
t2.micro on AWS
ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220914

**Comment by slice4e** [comment]
Not reproducible now.
