### ISSUE TITLE
[BUG]: regression_comment.edit(comment_body) on coordinator should handle failed/missing comment

### ISSUE THREAD

**Issue by fcostaoliveira** [redis/redis-benchmarks-specification#252]
```
	
2024-07-26 20:59:33 INFO Consuming from group runners-cg:redis/redis/commits-intel64-ubuntu22.04-redis-icx1. Consumer id runners-cg:redis/redis/commits-intel64-ubuntu22.04-redis-icx1-self-contained-proc#1
	
	
	
	
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/issues/comments#update-an-issue-comment", "status": "404"}
	
	
    raise self.__createException(status, responseHeaders, output)
	
	
  File "/usr/local/lib/python3.10/dist-packages/github/Requester.py", line 423, in __check
	
	
    return self.__check(
	
	
  File "/usr/local/lib/python3.10/dist-packages/github/Requester.py", line 398, in requestJsonAndCheck
	
	
    headers, data = self._requester.requestJsonAndCheck(
	
	
  File "/usr/local/lib/python3.10/dist-packages/github/IssueComment.py", line 130, in edit
	
	
    regression_comment.edit(comment_body)
	
	
  File "/usr/local/lib/python3.10/dist-packages/redis_benchmarks_specification/__common__/github.py", line 142, in update_comment_if_needed
	
	
    update_comment_if_needed(
```

**Comment by fcostaoliveira** [comment]
Same happened:
```
2024-09-18 06:42:56 INFO Removing temporary dirs /root/tmpz9gvyw5q and /root/tmp5k_u_3cb
2024-09-18 06:42:57 INFO The old github comment is different from the new comment. updating it...
2024-09-18 06:42:57 INFO Updated github comment with latest test info https://github.com/redis/redis/pull/13359#issuecomment-2358244011
2024-09-18 06:42:57 INFO Detected github token
2024-09-18 06:42:58 CRITICAL Some unexpected exception was caught during local work on stream 1726666888587-0. Failing test....
2024-09-18 06:42:58 CRITICAL Exception type: UnknownObjectException
2024-09-18 06:42:58 CRITICAL Exception message: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/issues/issues#get-an-issue", "status": "404"}
2024-09-18 06:42:58 CRITICAL Traceback details:
2024-09-18 06:42:58 CRITICAL Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py", line 1342, in process_self_contained_coordinator_stream
    ) = check_github_available_and_actionable(
  File "/usr/local/lib/python3.10/dist-packages/redis_benchmarks_specification/__common__/github.py", line 114, in check_github_available_and_actionable
    .get_issue(pull_request_n)
  File "/usr/local/lib/python3.10/dist-packages/github/Repository.py", line 2527, in get_issue
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.10/dist-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.10/dist-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/issues/issues#get-an-issue", "status": "404"}

```
